### ISSUE TITLE
Documentation mentions missing/outdated Layout-Addon

### ISSUE THREAD

**Issue by nkfilis** [Cockpit-HQ/docs#5]
The documentation at https://getcockpit.com/documentation/core/concepts/field-types#layout mentions a "Layoutaddon" which seems to mean this one https://github.com/agentejo/LayoutComponents which seems to be for an older version of Cockpit. Maybe the documentation should link to the correct one if it exists or remove the whole section if it's obsolete?

**Comment by aheinze** [comment]
The documentation mentions the new layout addon included in the pro version
